runtime: python37

handlers:
- url: /.well-known/acme-challenge
  static_dir: letsencrypt
- url: /styles
  static_dir: styles
- url: /js
  static_dir: js
- url: /img
  static_dir: images
- url: /.*
  script: auto
